import Foundation

public struct SwiftUIEmissionOptions: Sendable {
  public var viewName: String

  public init(viewName: String = "GeneratedView") {
    self.viewName = viewName
  }
}

public struct SwiftUIEmitter: Sendable {
  public var options: SwiftUIEmissionOptions

  public init(options: SwiftUIEmissionOptions = .init()) {
    self.options = options
  }

  public func emit(_ analysis: LoomAnalysis) -> String {
    var lines: [String] = [
      "// Generated by Loom. Review diagnostics before integrating.",
      "import SwiftUI",
      "",
      "struct \(safeTypeName(options.viewName)): View {",
      "    var body: some View {",
    ]
    let children = analysis.layout.children
    if children.count == 1, let child = children.first {
      emit(child, indent: 2, into: &lines)
    } else {
      lines.append("        ZStack {")
      for child in children {
        emit(child, indent: 3, into: &lines)
      }
      lines.append("        }")
    }
    lines.append("    }")
    lines.append("}")
    return lines.joined(separator: "\n") + "\n"
  }

  private func emit(_ node: LoomNode, indent: Int, into lines: inout [String]) {
    let prefix = String(repeating: "    ", count: indent)
    switch node.kind {
    case .root, .overlayStack, .geometryReader, .grid:
      lines.append("\(prefix)ZStack {")
      appendUnsupportedCommentIfNeeded(node, indent: indent + 1, into: &lines)
      emitChildren(node.children, indent: indent + 1, into: &lines)
      lines.append("\(prefix)}")
      appendModifiers(node, indent: indent, into: &lines)
    case .verticalStack:
      emitContainer("VStack", node: node, indent: indent, into: &lines)
    case .horizontalStack, .splitView:
      emitContainer("HStack", node: node, indent: indent, into: &lines)
    case .scrollView:
      lines.append("\(prefix)ScrollView {")
      emitChildren(node.children, indent: indent + 1, into: &lines)
      lines.append("\(prefix)}")
      appendModifiers(node, indent: indent, into: &lines)
    case .list:
      lines.append("\(prefix)List {")
      if node.children.isEmpty {
        lines.append("\(prefix)    Text(\"Bind list rows\")")
      } else {
        emitChildren(node.children, indent: indent + 1, into: &lines)
      }
      lines.append("\(prefix)}")
      appendModifiers(node, indent: indent, into: &lines)
    case .text:
      lines.append("\(prefix)Text(\(stringLiteralValue(node.arguments, fallback: "")))")
      appendModifiers(node, indent: indent, into: &lines)
    case .textField:
      lines.append(
        "\(prefix)TextField(\(stringLiteralValue(node.arguments, fallback: "")), text: .constant(\"\"))"
      )
      appendModifiers(node, indent: indent, into: &lines)
    case .button:
      let label = stringLiteralValue(node.arguments, fallback: "Action")
      lines.append("\(prefix)Button(\(label)) {")
      lines.append("\(prefix)    // Wire action")
      lines.append("\(prefix)}")
      appendModifiers(node, indent: indent, into: &lines)
    case .image:
      lines.append("\(prefix)Image(\(stringLiteralValue(node.arguments, fallback: "")))")
      appendModifiers(node, indent: indent, into: &lines)
    case .slider:
      if node.expression == "ProgressBar" {
        lines.append("\(prefix)ProgressView(value: 0)")
      } else {
        lines.append("\(prefix)Slider(value: .constant(0))")
      }
      appendModifiers(node, indent: indent, into: &lines)
    case .toggle:
      lines.append("\(prefix)Toggle(\"\", isOn: .constant(false))")
      appendModifiers(node, indent: indent, into: &lines)
    case .spacer:
      lines.append("\(prefix)Spacer()")
    case .divider:
      lines.append("\(prefix)Divider()")
    case .conditional:
      lines.append("\(prefix)if true {")
      lines.append("\(prefix)    // Restore condition from source")
      emitChildren(node.children, indent: indent + 1, into: &lines)
      lines.append("\(prefix)}")
    case .loop:
      lines.append("\(prefix)ForEach(Array(0..<1), id: \\.self) { _ in")
      emitChildren(node.children, indent: indent + 1, into: &lines)
      lines.append("\(prefix)}")
    case .color:
      lines.append("\(prefix)Color.clear")
      appendModifiers(node, indent: indent, into: &lines)
    case .component:
      lines.append("\(prefix)// Unsupported XAML component: \(safeComment(node.expression))")
      if node.children.isEmpty {
        lines.append("\(prefix)EmptyView()")
      } else {
        emitChildren(node.children, indent: indent, into: &lines)
      }
    case .unsupported:
      lines.append("\(prefix)// Unsupported source: \(safeComment(node.expression))")
      lines.append("\(prefix)EmptyView()")
    }
  }

  private func emitContainer(
    _ name: String,
    node: LoomNode,
    indent: Int,
    into lines: inout [String]
  ) {
    let prefix = String(repeating: "    ", count: indent)
    let spacing = node.properties["xaml.Spacing"].flatMap(numericValue)
    let suffix = spacing.map { "(spacing: \($0))" } ?? " {"
    if spacing == nil {
      lines.append("\(prefix)\(name) {")
    } else {
      lines.append("\(prefix)\(name)\(suffix) {")
    }
    emitChildren(node.children, indent: indent + 1, into: &lines)
    lines.append("\(prefix)}")
    appendModifiers(node, indent: indent, into: &lines)
  }

  private func emitChildren(_ children: [LoomNode], indent: Int, into lines: inout [String]) {
    if children.isEmpty {
      lines.append("\(String(repeating: "    ", count: indent))EmptyView()")
      return
    }
    for child in children {
      emit(child, indent: indent, into: &lines)
    }
  }

  private func appendUnsupportedCommentIfNeeded(
    _ node: LoomNode,
    indent: Int,
    into lines: inout [String]
  ) {
    guard let element = node.properties["xamlElement"], node.kind == .root else { return }
    lines.append(
      "\(String(repeating: "    ", count: indent))// XAML container normalized from \(safeComment(element))"
    )
  }

  private func appendModifiers(_ node: LoomNode, indent: Int, into lines: inout [String]) {
    let prefix = String(repeating: "    ", count: indent)
    if let frame = node.modifiers.first(where: { $0.name == "frame" }) {
      let labels = labeledArguments(frame.arguments)
      let width = labels["width"].flatMap(numericValue)
      let height = labels["height"].flatMap(numericValue)
      if width != nil || height != nil {
        let widthPart = width.map { "width: \($0)" }
        let heightPart = height.map { "height: \($0)" }
        lines.append(
          "\(prefix)    .frame(\([widthPart, heightPart].compactMap { $0 }.joined(separator: ", ")))"
        )
      }
    }
    if let identifier = node.modifiers.first(where: { $0.name == "accessibilityIdentifier" }) {
      lines.append("\(prefix)    .accessibilityIdentifier(\(identifier.arguments))")
    }
  }

  private func labeledArguments(_ arguments: String) -> [String: String] {
    var result: [String: String] = [:]
    for part in arguments.split(separator: ",") {
      guard let colon = part.firstIndex(of: ":") else { continue }
      let key = part[..<colon].trimmingCharacters(in: .whitespacesAndNewlines)
      let value = part[part.index(after: colon)...].trimmingCharacters(in: .whitespacesAndNewlines)
      result[key] = value
    }
    return result
  }

  private func numericValue(_ value: String) -> String? {
    let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
    guard trimmed.range(of: #"^-?[0-9]+(?:\.[0-9]+)?$"#, options: .regularExpression) != nil
    else { return nil }
    return trimmed
  }

  private func stringLiteralValue(_ value: String, fallback: String) -> String {
    let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
    if trimmed.hasPrefix("\""), trimmed.hasSuffix("\"") { return trimmed }
    return "\"\(escapeSwiftString(fallback))\""
  }

  private func safeTypeName(_ value: String) -> String {
    let filtered = value.filter { $0.isLetter || $0.isNumber || $0 == "_" }
    guard let first = filtered.first else { return "GeneratedView" }
    let capitalized = first.uppercased() + filtered.dropFirst()
    return capitalized.first?.isNumber == true ? "Generated\(capitalized)" : capitalized
  }

  private func escapeSwiftString(_ value: String) -> String {
    value.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
  }

  private func safeComment(_ value: String) -> String {
    value.replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: "*/", with: "* /")
  }
}
