import Foundation

public struct XAMLEmissionOptions: Sendable {
  public var themeResourcePrefix: String?
  public var includePatternComments: Bool

  public init(themeResourcePrefix: String? = nil, includePatternComments: Bool = false) {
    self.themeResourcePrefix = themeResourcePrefix
    self.includePatternComments = includePatternComments
  }

  var backgroundBrush: String {
    if let themeResourcePrefix { return "{ThemeResource \(themeResourcePrefix)CanvasBrush}" }
    return "{ThemeResource ApplicationPageBackgroundThemeBrush}"
  }

  var dividerBrush: String {
    if let themeResourcePrefix { return "{ThemeResource \(themeResourcePrefix)BorderBrush}" }
    return "{ThemeResource SystemControlForegroundBaseLowBrush}"
  }
}

public struct XAMLEmitter: Sendable {
  public var options: XAMLEmissionOptions
  public var patternRegistry: LoomPatternRegistry?

  public init(options: XAMLEmissionOptions = .init(), patternRegistry: LoomPatternRegistry? = nil) {
    self.options = options
    self.patternRegistry = patternRegistry
  }

  public func emit(_ analysis: LoomAnalysis) -> String {
    var lines: [String] = []
    lines.append("<!-- Generated by Loom. Review diagnostics before integrating. -->")
    lines.append("<Grid")
    lines.append("    xmlns=\"http://schemas.microsoft.com/winfx/2006/xaml/presentation\"")
    lines.append("    xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\">")
    lines.append(
      "    <!-- Source: \(xmlComment(analysis.sourcePath)); \(xmlComment(analysis.rootView)).\(xmlComment(analysis.component)) -->"
    )

    for diagnostic in analysis.diagnostics where diagnostic.severity != .info {
      lines.append("    <!-- \(diagnostic.code): \(xmlComment(diagnostic.message)) -->")
    }
    for child in analysis.layout.children {
      emit(child, indent: 1, placement: nil, into: &lines)
    }
    lines.append("</Grid>")
    return lines.joined(separator: "\n") + "\n"
  }

  private func emit(
    _ node: LoomNode,
    indent: Int,
    placement: String?,
    into lines: inout [String]
  ) {
    let prefix = String(repeating: "    ", count: indent)
    appendPatternComment(for: node, prefix: prefix, into: &lines)
    switch node.kind {
    case .root, .overlayStack, .geometryReader:
      let attributes = commonAttributes(node, placement: placement)
      lines.append("\(prefix)<Grid\(attributes)>")
      if node.kind == .geometryReader {
        lines.append(
          "\(prefix)    <!-- GeometryReader: connect runtime width/height through SizeChanged or the view model. -->"
        )
      }
      for child in node.children {
        emit(child, indent: indent + 1, placement: nil, into: &lines)
      }
      lines.append("\(prefix)</Grid>")

    case .verticalStack:
      emitLinearGrid(node, horizontal: false, indent: indent, placement: placement, into: &lines)
    case .horizontalStack, .splitView:
      emitLinearGrid(node, horizontal: true, indent: indent, placement: placement, into: &lines)
    case .grid:
      lines.append("\(prefix)<Grid\(commonAttributes(node, placement: placement))>")
      lines.append(
        "\(prefix)    <!-- SwiftUI grid definition requires an explicit WinUI row/column policy. -->"
      )
      for child in node.children {
        emit(child, indent: indent + 1, placement: nil, into: &lines)
      }
      lines.append("\(prefix)</Grid>")
    case .scrollView:
      lines.append("\(prefix)<ScrollViewer\(commonAttributes(node, placement: placement))>")
      emitSingleOrWrappedChildren(node.children, indent: indent + 1, into: &lines)
      lines.append("\(prefix)</ScrollViewer>")
    case .list:
      lines.append("\(prefix)<ListView\(commonAttributes(node, placement: placement))>")
      lines.append(
        "\(prefix)    <!-- Bind ItemsSource and supply a DataTemplate for \(xmlComment(node.expression)). -->"
      )
      lines.append("\(prefix)</ListView>")
    case .text:
      let text = textValue(for: node)
      lines.append(
        "\(prefix)<TextBlock Text=\"\(xmlAttribute(text))\"\(commonAttributes(node, placement: placement)) />"
      )
    case .textField:
      let placeholder = firstStringLiteral(in: node.arguments) ?? ""
      lines.append(
        "\(prefix)<TextBox PlaceholderText=\"\(xmlAttribute(placeholder))\"\(commonAttributes(node, placement: placement)) />"
      )
    case .button:
      let content = firstStringLiteral(in: node.arguments) ?? "Action"
      lines.append(
        "\(prefix)<Button Content=\"\(xmlAttribute(content))\"\(commonAttributes(node, placement: placement))>"
      )
      if !node.children.isEmpty {
        lines.append(
          "\(prefix)    <!-- SwiftUI Button closure may mix an action and label; wire Click/x:Bind manually. -->"
        )
      }
      lines.append("\(prefix)</Button>")
    case .image:
      let name = firstStringLiteral(in: node.arguments) ?? ""
      lines.append(
        "\(prefix)<Image Source=\"\(xmlAttribute(name))\"\(commonAttributes(node, placement: placement)) />"
      )
    case .slider:
      let element = node.expression == "ProgressView" ? "ProgressBar" : "Slider"
      lines.append("\(prefix)<\(element)\(commonAttributes(node, placement: placement)) />")
    case .toggle:
      lines.append("\(prefix)<ToggleSwitch\(commonAttributes(node, placement: placement)) />")
    case .spacer:
      lines.append("\(prefix)<Grid\(placement.map { " \($0)" } ?? "") />")
    case .divider:
      lines.append(
        "\(prefix)<Rectangle Height=\"1\" Fill=\"\(options.dividerBrush)\"\(placement.map { " \($0)" } ?? "") />"
      )
    case .conditional:
      lines.append("\(prefix)<Grid\(placement.map { " \($0)" } ?? "")>")
      lines.append(
        "\(prefix)    <!-- SwiftUI condition: \(xmlComment(node.properties["condition"] ?? "unknown")). Bind Visibility or use VisualStateManager. -->"
      )
      for child in node.children {
        emit(child, indent: indent + 1, placement: nil, into: &lines)
      }
      lines.append("\(prefix)</Grid>")
    case .loop:
      lines.append("\(prefix)<ListView\(commonAttributes(node, placement: placement))>")
      lines.append(
        "\(prefix)    <!-- ForEach \(xmlComment(node.arguments)): bind ItemsSource and translate the child tree into ItemTemplate. -->"
      )
      lines.append("\(prefix)</ListView>")
    case .color:
      lines.append(
        "\(prefix)<Border Background=\"\(options.backgroundBrush)\"\(commonAttributes(node, placement: placement)) />"
      )
    case .component:
      lines.append("\(prefix)<Grid\(commonAttributes(node, placement: placement))>")
      lines.append(
        "\(prefix)    <!-- Loom component reference: \(xmlComment(node.expression)). Generate separately or map to a UserControl. -->"
      )
      lines.append("\(prefix)</Grid>")
    case .unsupported:
      lines.append("\(prefix)<!-- Unsupported SwiftUI: \(xmlComment(node.expression)) -->")
    }
  }

  private func emitLinearGrid(
    _ node: LoomNode,
    horizontal: Bool,
    indent: Int,
    placement: String?,
    into lines: inout [String]
  ) {
    let prefix = String(repeating: "    ", count: indent)
    lines.append("\(prefix)<Grid\(commonAttributes(node, placement: placement))>")
    let definition = horizontal ? "ColumnDefinition" : "RowDefinition"
    let definitions = horizontal ? "Grid.ColumnDefinitions" : "Grid.RowDefinitions"
    lines.append("\(prefix)    <\(definitions)>")
    for child in node.children {
      let dimension = dimensionAttributes(for: child, horizontal: horizontal)
      lines.append("\(prefix)        <\(definition)\(dimension) />")
    }
    lines.append("\(prefix)    </\(definitions)>")
    if node.kind == .splitView {
      lines.append(
        "\(prefix)    <!-- SplitView: add pointer-driven resizing or a project-specific splitter control. -->"
      )
    }
    for (index, child) in node.children.enumerated() {
      let placement = horizontal ? "Grid.Column=\"\(index)\"" : "Grid.Row=\"\(index)\""
      emit(child, indent: indent + 1, placement: placement, into: &lines)
    }
    lines.append("\(prefix)</Grid>")
  }

  private func emitSingleOrWrappedChildren(
    _ children: [LoomNode],
    indent: Int,
    into lines: inout [String]
  ) {
    if children.count == 1, let child = children.first {
      emit(child, indent: indent, placement: nil, into: &lines)
      return
    }
    let prefix = String(repeating: "    ", count: indent)
    lines.append("\(prefix)<StackPanel>")
    for child in children {
      emit(child, indent: indent + 1, placement: nil, into: &lines)
    }
    lines.append("\(prefix)</StackPanel>")
  }

  private func appendPatternComment(for node: LoomNode, prefix: String, into lines: inout [String]) {
    guard options.includePatternComments, let pattern = patternRegistry?.pattern(for: node.kind)
    else { return }
    let mapping = patternRegistry?.mapping(for: node.kind, platform: "winui3")
    let constructs = mapping?.constructs.joined(separator: ", ") ?? "unmapped"
    lines.append(
      "\(prefix)<!-- Loom pattern: \(xmlComment(pattern.id)) -> winui3 \(xmlComment(constructs)) -->"
    )
  }

  private func dimensionAttributes(for node: LoomNode, horizontal: Bool) -> String {
    if node.kind == .spacer { return horizontal ? " Width=\"*\"" : " Height=\"*\"" }
    guard let frame = node.modifiers.first(where: { $0.name == "frame" }) else {
      let flexibleKinds: Set<LoomNodeKind> = [.splitView, .scrollView, .list, .geometryReader]
      let flexible =
        flexibleKinds.contains(node.kind)
        || descendantRequestsInfinity(node, horizontal: horizontal)
      if horizontal { return flexible ? " Width=\"*\"" : " Width=\"Auto\"" }
      return flexible ? " Height=\"*\"" : " Height=\"Auto\""
    }
    let labels = labeledArguments(frame.arguments)
    var attributes = ""
    if horizontal {
      if let ideal = numericValue(labels["idealWidth"]) {
        attributes += " Width=\"\(ideal)*\""
      } else {
        let isFlexible = labels["maxWidth"]?.contains("infinity") == true
        attributes += isFlexible ? " Width=\"*\"" : " Width=\"Auto\""
      }
      if let value = numericValue(labels["minWidth"]) { attributes += " MinWidth=\"\(value)\"" }
      if let value = numericValue(labels["maxWidth"]) { attributes += " MaxWidth=\"\(value)\"" }
    } else {
      if let ideal = numericValue(labels["idealHeight"]) {
        attributes += " Height=\"\(ideal)*\""
      } else {
        let isFlexible = labels["maxHeight"]?.contains("infinity") == true
        attributes += isFlexible ? " Height=\"*\"" : " Height=\"Auto\""
      }
      if let value = numericValue(labels["minHeight"]) { attributes += " MinHeight=\"\(value)\"" }
      if let value = numericValue(labels["maxHeight"]) { attributes += " MaxHeight=\"\(value)\"" }
    }
    return attributes
  }

  private func commonAttributes(_ node: LoomNode, placement: String?) -> String {
    var values: [String] = []
    if let placement { values.append(placement) }
    let containerArguments = labeledArguments(node.arguments)
    if let spacing = numericValue(containerArguments["spacing"]) {
      if node.kind == .horizontalStack { values.append("ColumnSpacing=\"\(spacing)\"") }
      if node.kind == .verticalStack { values.append("RowSpacing=\"\(spacing)\"") }
    }
    if let frame = node.modifiers.first(where: { $0.name == "frame" }) {
      let labels = labeledArguments(frame.arguments)
      for (swiftName, xamlName) in [
        ("minWidth", "MinWidth"), ("maxWidth", "MaxWidth"),
        ("minHeight", "MinHeight"), ("maxHeight", "MaxHeight"),
      ] {
        if let value = numericValue(labels[swiftName]) {
          values.append("\(xamlName)=\"\(value)\"")
        }
      }
      if let width = numericValue(labels["width"] ?? unlabeledFirst(frame.arguments)) {
        values.append("Width=\"\(width)\"")
      }
      if let height = numericValue(labels["height"]) {
        values.append("Height=\"\(height)\"")
      }
    }
    let paddings = node.modifiers.filter { $0.name == "padding" }
    if let translated = combinedPadding(paddings) {
      values.append("Margin=\"\(translated)\"")
    }
    if let accessibility = node.modifiers.first(where: {
      $0.name == "accessibilityIdentifier" || $0.name == "accessibilityLabel"
    }), let value = firstStringLiteral(in: accessibility.arguments) {
      values.append("AutomationProperties.AutomationId=\"\(xmlAttribute(value))\"")
    }
    return values.isEmpty ? "" : " " + values.joined(separator: " ")
  }

  private func combinedPadding(_ modifiers: [LoomModifier]) -> String? {
    guard !modifiers.isEmpty else { return nil }
    var left = 0.0
    var top = 0.0
    var right = 0.0
    var bottom = 0.0
    var translatedAny = false
    for modifier in modifiers {
      let parts = splitTopLevel(modifier.arguments)
      if parts.count == 1, let value = Double(parts[0]) {
        left += value
        top += value
        right += value
        bottom += value
        translatedAny = true
        continue
      }
      guard parts.count >= 2, let raw = parts.last, let value = Double(raw) else { continue }
      if parts[0].contains("horizontal") {
        left += value
        right += value
        translatedAny = true
      } else if parts[0].contains("vertical") {
        top += value
        bottom += value
        translatedAny = true
      } else if parts[0].contains("top") {
        top += value
        translatedAny = true
      } else if parts[0].contains("bottom") {
        bottom += value
        translatedAny = true
      } else if parts[0].contains("leading") {
        left += value
        translatedAny = true
      } else if parts[0].contains("trailing") {
        right += value
        translatedAny = true
      }
    }
    guard translatedAny else { return nil }
    if left == top && top == right && right == bottom { return formatNumber(left) }
    if left == right && top == bottom { return "\(formatNumber(left)),\(formatNumber(top))" }
    return
      "\(formatNumber(left)),\(formatNumber(top)),\(formatNumber(right)),\(formatNumber(bottom))"
  }

  private func descendantRequestsInfinity(_ node: LoomNode, horizontal: Bool) -> Bool {
    let label = horizontal ? "maxWidth" : "maxHeight"
    if node.modifiers.contains(where: {
      $0.name == "frame" && labeledArguments($0.arguments)[label]?.contains("infinity") == true
    }) {
      return true
    }
    return node.children.contains { descendantRequestsInfinity($0, horizontal: horizontal) }
  }

  private func formatNumber(_ value: Double) -> String {
    value.rounded() == value ? String(Int(value)) : String(value)
  }

  private func labeledArguments(_ arguments: String) -> [String: String] {
    var result: [String: String] = [:]
    for part in splitTopLevel(arguments) {
      guard let colon = part.firstIndex(of: ":") else { continue }
      let key = part[..<colon].trimmingCharacters(in: .whitespacesAndNewlines)
      let value = part[part.index(after: colon)...].trimmingCharacters(in: .whitespacesAndNewlines)
      result[key] = value
    }
    return result
  }

  private func splitTopLevel(_ text: String) -> [String] {
    var result: [String] = []
    var current = ""
    var depth = 0
    var inString = false
    var escaping = false
    for character in text {
      if inString {
        current.append(character)
        if escaping {
          escaping = false
        } else if character == "\\" {
          escaping = true
        } else if character == "\"" {
          inString = false
        }
        continue
      }
      if character == "\"" {
        inString = true
        current.append(character)
      } else if character == "(" || character == "[" || character == "{" {
        depth += 1
        current.append(character)
      } else if character == ")" || character == "]" || character == "}" {
        depth = max(0, depth - 1)
        current.append(character)
      } else if character == "," && depth == 0 {
        result.append(current.trimmingCharacters(in: .whitespacesAndNewlines))
        current = ""
      } else {
        current.append(character)
      }
    }
    if !current.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
      result.append(current.trimmingCharacters(in: .whitespacesAndNewlines))
    }
    return result
  }

  private func unlabeledFirst(_ arguments: String) -> String? {
    splitTopLevel(arguments).first(where: { !$0.contains(":") })
  }

  private func numericValue(_ value: String?) -> String? {
    guard let value else { return nil }
    let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
    guard trimmed.range(of: #"^-?[0-9]+(?:\.[0-9]+)?$"#, options: .regularExpression) != nil else {
      return nil
    }
    return trimmed
  }

  private func firstStringLiteral(in text: String) -> String? {
    guard let first = text.firstIndex(of: "\"") else { return nil }
    var index = text.index(after: first)
    var result = ""
    var escaping = false
    while index < text.endIndex {
      let character = text[index]
      if escaping {
        result.append(character)
        escaping = false
      } else if character == "\\" {
        escaping = true
      } else if character == "\"" {
        return result
      } else {
        result.append(character)
      }
      index = text.index(after: index)
    }
    return nil
  }

  private func textValue(for node: LoomNode) -> String {
    if let literal = firstStringLiteral(in: node.arguments) { return literal }
    let expression = node.arguments.trimmingCharacters(in: .whitespacesAndNewlines)
    if expression.range(of: #"^[A-Za-z_][A-Za-z0-9_.]*$"#, options: .regularExpression) != nil {
      return "{Binding \(expression)}"
    }
    return "{Binding}"
  }

  private func xmlAttribute(_ value: String) -> String {
    value
      .replacingOccurrences(of: "&", with: "&amp;")
      .replacingOccurrences(of: "\"", with: "&quot;")
      .replacingOccurrences(of: "<", with: "&lt;")
      .replacingOccurrences(of: ">", with: "&gt;")
  }

  private func xmlComment(_ value: String) -> String {
    value
      .replacingOccurrences(of: "--", with: "—")
      .replacingOccurrences(of: "<", with: "&lt;")
      .replacingOccurrences(of: ">", with: "&gt;")
      .replacingOccurrences(of: "\n", with: " ")
  }
}
